name: Version Increment Check

on:
  pull_request:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current version
      id: get_version
      run: |
        current_version=$(grep -oP 'pico_set_program_version\(\$\{PROGRAM_NAME\} "\K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
        echo "current_version=${current_version}" >> $GITHUB_ENV

    - name: Get previous version
      id: get_previous_version
      run: |
        previous_version=$(git show origin/main:CMakeLists.txt | grep -oP 'pico_set_program_version\(\$\{PROGRAM_NAME\} "\K[0-9]+\.[0-9]+\.[0-9]+')
        echo "previous_version=${previous_version}" >> $GITHUB_ENV

    - name: Compare versions
      run: |
        if [[ "${{ env.current_version }}" == "${{ env.previous_version }}" ]]; then
          echo "Version has not been incremented."
          exit 1
        else
          echo "Version has been incremented."
        fi

    - name: Allow merge if version is incremented
      if: success()
      run: echo "Version increment verified, pull request can be merged."